package com.sample

import logic.*;
import java.util.Scanner;
 
// REGRAS SEM DIAGNOSTICOS ANTERIORES

rule "Paciente tem 1 nodulo menor de 1cm"
salience 90
	when
		$p:Paciente (getLastDiag().checkSizeNoduloMenor(1))
	then
		System.out.println("Repetir ultrassom em 4 meses");
		$p.setNomeTratamento("Inconclusivo, repetir ultrassom em 4 meses");
		drools.halt();
end

rule "Paciente tem nodulo entre 1 a 2 cm"
salience 90	
	when
		$p:Paciente (getLastDiag().checkSizeNoduloEntre(1, 2))
	then
		if ($p.historico.get(0).getFourPhaseCT() >= 2){
			System.out.println("HCC");
			$p.getLastDiag().setResultado(true);
		}else
			if($p.historico.get(0).getBiopsia() == true){
				System.out.println("HCC");
				$p.getLastDiag().setResultado(true);
			}else{
				System.out.println("Inconclusivo!");
				System.out.println("Repetir ultrassom em 4 meses");
				$p.setNomeTratamento("Inconclusivo, repetir ultrassom em 4 meses");
				drools.halt();
		}
end

rule "Paciente tem nodulo maior ou igual a 2 cm"
salience 90	
	when//erro aqui quando nodulos != 3
		$p:Paciente (getLastDiag().checkSizeNoduloMaior(2) == true)
	then
		if ($p.getLastDiag().getFourPhaseCT() >= 1){
			System.out.println("HCC");
			$p.getLastDiag().setResultado(true);
		}else
			if($p.getLastDiag().getBiopsia() == true){
				System.out.println("HCC");
				$p.getLastDiag().setResultado(true);
			}else{
				System.out.println("Inconclusivo!");
				$p.setNomeTratamento("Inconclusivo, repetir ultrassom em 4 meses");
				drools.halt();
		}
end

rule "Stage 0"
salience 88
	when
		$p:Paciente(getLastDiag().getNodulos() == 1, 
		getLastDiag().checkSizeNoduloMenor(2), 
		getLastDiag().getFeelsWell() && getLastDiag().getLiverWorksNormally(),
		!getLastDiag().getNeedsHelp(),
		!getLastDiag().getSevereLiverDamage())
	then
		$p.setStage('0');
		$p.getLastDiag().setNeedsHelp(false);
		$p.getLastDiag().setSevereLiverDamage(false);
		
end

rule "Stage A single tumor"
salience 87
	when
		$p:Paciente(getLastDiag().getNodulos() == 1,
		getLastDiag().checkSizeNoduloMenor(5) && getStage() != '0',
		getLastDiag().getFeelsWell() && getLastDiag().getLiverWorksNormally(),
		!getLastDiag().getNeedsHelp(),
		!getLastDiag().getSevereLiverDamage())
	then
		$p.setStage('A');
end

rule "Stage A multiple tumor"
salience 87
	when
		$p:Paciente(getLastDiag().getNodulos() <= 3,
		getLastDiag().getFeelsWell() && getLastDiag().getLiverWorksNormally(),
	    getLastDiag().checkSizeNoduloMenor(3),
	    !getLastDiag().getNeedsHelp(),
		!getLastDiag().getSevereLiverDamage())
	then
		$p.setStage('A');
end

rule "Stage B"
salience 86
	when
		$p:Paciente(getStage()!='0' && getStage()!='A',
		   getLastDiag().getFeelsWell() && getLastDiag().getLiverWorksNormally(),
		   getLastDiag().getNodulos() > 3,
		   !getLastDiag().getNeedsHelp(),
		   !getLastDiag().getSevereLiverDamage())
	then
		$p.setStage('B');
end

rule "Stage C"
salience 85
	when
		$p:Paciente((getLastDiag().getHasSpread() || !getLastDiag().getFeelsWell()) && getLastDiag().getLiverWorksNormally(),
		   getStage()!='0' && getStage()!='A' && getStage()!='B',
		   !getLastDiag().getNeedsHelp(),
		   !getLastDiag().getSevereLiverDamage()) 
	then
		$p.setStage('C');
end

rule "Stage D"
salience 84
	when
		$p:Paciente(getLastDiag().getSevereLiverDamage || getLastDiag().getNeedsHelp,
		   getStage()!='0' && getStage()!='A' && getStage()!='B' && getStage()!='C',
		   !getLastDiag().getNeedsHelp(),
		   !getLastDiag().getSevereLiverDamage()) 
	then
		$p.setStage('D');
end

//REGRAS COMUNS

rule "Very early stage single"
salience 80
	when
		$p:Paciente (getStage()== '0',
		   getLastDiag().getNodulos()== 1)
	then
		if ($p.getLastDiag().getPortalSpread() == false){
			System.out.println("Recessao");
			$p.setNomeTratamento("Recessao");
			drools.halt();
		}else
			if ($p.getLastDiag().getHasAssociatedDiseases() == false){
				System.out.println("Transplante Figado CLT/LDLT");
				$p.setNomeTratamento("Transplante Figado CLT/LDLT");
				drools.halt();
			}else{
				System.out.println("Radiofrequency ablation RF/PEI");
				$p.setNomeTratamento("RF/PEI");
				drools.halt();
			}
end

rule "Very early stage multiple"
salience 80
	when
		$p:Paciente (getStage()=='0')
		   Paciente(getLastDiag().getNodulos()>1)
	then
		if ($p.getLastDiag().getHasAssociatedDiseases() == false){
			System.out.println("Transplante Figado CLT/LDLT");
			$p.setNomeTratamento("Transplante Figado CLT/LDLT");
			drools.halt();
		}else{
			System.out.println("Radiofrequency ablation RF/PEI");
			$p.setNomeTratamento("RF/PEI");
			drools.halt();
		}
end

rule "Early stage"
salience 80
	when
		$p:Paciente (getStage()=='A')
		   Paciente(getLastDiag().getNodulos()>1)
	then
		if ($p.getLastDiag().getHasAssociatedDiseases() == false){
			System.out.println("Transplante Figado CLT/LDLT");
			$p.setNomeTratamento("Transplante Figado CLT/LDLT");
			drools.halt();
		}else{
			System.out.println("Radiofrequency ablation RF/PEI");
			$p.setNomeTratamento("RF/PEI");
			drools.halt();
		}
end

rule "Intermediate stage"
salience 80
	when
		$p:Paciente (getStage()=='B')
	then
		System.out.println("Transarterial chemoembolization for liver cancer (TACE)");
		$p.setNomeTratamento("TACE");
		drools.halt();
end

rule "Advanced stage"
salience 80
	when
		$p:Paciente (getStage()=='C')
	then
		System.out.println("Sorafenib");
		$p.setNomeTratamento("Sorafenib");
		drools.halt();
end

rule "Terminal stage"
salience 80
	when 
		$p:Paciente (getStage()=='D')
	then
		System.out.println("Melhores cuidados de fim de vida");
		$p.setNomeTratamento("Melhores cuidados de fim de vida");
		drools.halt();
end

// REGRAS QUANDO EXISTIREM DIAGNOSTICOS ANTERIORES

rule "Returning patient"
salience 100
	when
		$p:Paciente(getDiagnosticos() > 1)
	then
		if ($p.getLastDiag().getNodulo(0).getGrowing() == true){
			System.out.println("Investigar de acordo com o tamanho!");
			$p.setNomeTratamento("Investigar de acordo com o tamanho!");
			drools.halt();
			}
		else
		{
			System.out.println("Inconclusivo!!");
			System.out.println("Repetir ultrassom em 4 meses");
			$p.setNomeTratamento("Inconclusivo, repetir ultrassom em 4 meses");
			drools.halt();
		}
end

rule "No nodules"
salience 95
	when
		$p:Paciente(getLastDiag().getNodulos()==0)
	then
		System.out.println("Voce é saudavel!");
		$p.setNomeTratamento("Saudavel");
		drools.halt();
end