package com.sample

import logic.*;
import java.util.Scanner;
 
  /*
rule "nome"
    when

    then

end
*/

// REGRAS SEM DIAGNOSTICOS ANTERIORES

rule "Paciente tem 1 nodulo menor de 1cm"
salience 90
	when
		$p:Paciente (historico.size() == 1)
		$d:Diagnostico(nodulo.size() == 1 && nodulo.get(0) < 1)
	then
		System.out.println("Repetir ultra-som em 4 meses");
end

rule "Paciente tem nodulo entre 1 a 2 cm"
salience 90	
	when
		$p:Paciente (historico.size() == 1)
		forall($n:Nodulo(getTam()>=1 && getTam()<2))
	then
		if ($p.historico.get(0).getFourPhaseCT() >= 1)
			System.out.println("BIG CANCER");
		else
			if($p.historico.get(0).getBiopsia() == true)
				System.out.println("BIG CANCER");
			else
				System.out.println("NO CANCER");
end

rule "Paciente tem nodulo maior ou igual a 2 cm"
salience 90	
	when
		$p:Paciente (historico.size() == 1)
		forall($n:Nodulo(getTam()>= 2))
	then
		if	($p.historico.get(0).getFourPhaseCT()>= 1)
			System.out.println("BIG CANCER");
		else
			if($p.historico.get(0).getBiopsia() == true)
				System.out.println("BIG CANCER");
			else
				System.out.println("NO CANCER");
end

rule "Stage 0"
salience 85
	when
		$p:Paciente(historico.size() == 1, 
		historico.get(0).getNodulos() == 1, 
		historico.get(0).getNodulo().getTam()<2, 
		getFeelsWell()==true && getLiverWorksNormally()==true)
	then
		$p.setStage('0');
end

rule "Stage A single tumor"
salience 85
	when
		$p:Paciente(historico.size() == 1,
		historico.get(0).getNodulos() == 1,
		historico.get(0).getNodulo().getTam()<5 && getStage() != '0')
		$d:Diagnostico(getFeelsWell()==true && getLiverWorksNormally()==true) from $p.historico.get(0)
	then
		$p.setStage('A');
end

rule "Stage A multiple tumor"
salience 85
	when
		$p:Paciente(historico.size() == 1,
		historico.get(0).getNodulos() <= 3,
		getFeelsWell()==true && getLiverWorksNormally()==true)
		$n: Nodulo(getTam()<3) from $p.historico.get(0)
	then
		$p.setStage('A');
end

rule "Stage B"
salience 85
	when
		$p:Paciente(historico.size() == 1,
		getStage()!='0' && getStage()!='A')
		$d.Diagnostico(getFeelsWell()==true && getLiverWorksNormally()==true) from $p.historico.get(0)
	then
		$p.setStage('B');
end

rule "Stage C"
salience 85
	when
		$p:Paciente(historico.size() == 1)
		$d:Diagnostico((getHasSpread() == true || getFeelsWell() == false) && getLiverWorksNormally()==true) from from $p.historico.get(0) 
	then
		$p.setStage('C');
end

rule "Stage D"
salience 85
	when
		$p:Paciente(historico.size() == 1)
		$d:Diagnostico(getSevereLiverDamage == true || getNeedsHelp == true) from $p.historico.get(0)
	then
		$p.setStage('D');
end

rule "Very early stage single"
salience 80
	when
		$p:Paciente (historico.size()== 1)
		p:Paciente (getStage()== '0')
		$d:Diagnostico (nodulo.size()== 1)
	then
		if ($d.getPortalPressure() == false)
			System.out.println("RESSECTION");
		else
			if (d.getHasAssociatedDiseases() == false)
				System.out.println("TRANSPLANT");
			else
				System.out.println("Radiofrequency ablation");
end

rule "Very early stage multiple"
salience 80
	when
		$p:Paciente (historico.size() == 1)
		p:Paciente (stage.getStage()=='0')
		$d:Diagnostico (nodulo.size()>1)
	then
		if (d.getHasAssossiatedDiseases() == false)
			System.out.println("TRANSPLANT");
		else
			System.out.println("Radiofrequency ablation");
end

rule "Early stage"
salience 80
	when
		$p:Paciente (historico.size() == 1)
		$p:Paciente (stage.getStage()=='A')
		$d:Diagnostico (nodulo.size()>1)
	then
		if (d.hasAssossiatedDiseases == false)
			System.out.println("TRANSPLANT");
		else
			System.out.println("Radiofrequency ablation");
end

rule "Intermediate stage"
salience 80
	when
		$p:Paciente (historico.size() == 1)
		$p:Paciente (stage.getStage()=='B')
	then
		System.out.println("Transarterial chemoembolization for liver cancer.");
end

rule "Advanced stage"
salience 80
	when
		$p:Paciente (historico.size() == 1)
		$p:Paciente (stage.getStage()=='C')
	then
		System.out.println("Sorafenib");
end

rule "Terminal stage"
salience 80
	when 
		$p:Paciente (historico.size() == 1)
		$p:Paciente (stage.getStage()=='D')
	then
		System.out.println("Best supportive care");
end

// REGRAS QUANDO EXISTIREM DIAGNOSTICOS ANTERIORES